--liquibase formatted sql
--changeset piotrkorniak:4

CREATE TABLE BLOG_CATEGORIES (
    ID INT,
    BLOG_ID UUID,
    NAME VARCHAR(64),

    PRIMARY KEY (ID, BLOG_ID),
    FOREIGN KEY (BLOG_ID) REFERENCES SOURCES(ID)

);

CREATE TABLE POST_CATEGORIES (
    POST_ID UUID,
    CATEGORY_ID INT,
    BLOG_ID UUID,

    PRIMARY KEY (POST_ID, CATEGORY_ID, BLOG_ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(CONTENT_ID),
    FOREIGN KEY (CATEGORY_ID, BLOG_ID) REFERENCES BLOG_CATEGORIES(ID, BLOG_ID)

);