--liquibase formatted sql
--changeset piotrkorniak:5

CREATE TABLE CREATORS (
    ID UUID,
    NAME VARCHAR(128),

    PRIMARY KEY (ID)
);

CREATE TABLE BLOG_AUTHORS (
    ID INT,
    BLOG_ID UUID,

    CREATOR_ID UUID,
    NAME VARCHAR(128),
    DESCRIPTION VARCHAR(1024),
    LINK VARCHAR(128),

    PRIMARY KEY (ID, BLOG_ID),
    FOREIGN KEY (BLOG_ID) REFERENCES SOURCES(ID),
    FOREIGN KEY (CREATOR_ID) REFERENCES CREATORS(ID)
);

CREATE TABLE POST_AUTHORS (
    POST_ID UUID,
    AUTHOR_ID INT,
    BLOG_ID UUID,

    PRIMARY KEY (POST_ID, AUTHOR_ID, BLOG_ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(CONTENT_ID),
    FOREIGN KEY (AUTHOR_ID, BLOG_ID) REFERENCES BLOG_AUTHORS(ID, BLOG_ID)

);

CREATE TABLE CONTENT_CREATORS (
    CONTENT_ID UUID,
    CREATOR_ID UUID,

    PRIMARY KEY (CONTENT_ID, CREATOR_ID),
    FOREIGN KEY (CONTENT_ID) REFERENCES CONTENTS(ID),
    FOREIGN KEY (CREATOR_ID) REFERENCES CREATORS(ID)
)

