--liquibase formatted sql
--changeset piotrkorniak:6

CREATE TABLE BLOG_TAGS (
    ID INT,
    BLOG_ID UUID,
    NAME VARCHAR(128),

    PRIMARY KEY (ID, BLOG_ID),
    FOREIGN KEY (BLOG_ID) REFERENCES SOURCES(ID)

);

CREATE TABLE POST_TAGS (
    POST_ID UUID,
    TAG_ID INT,
    BLOG_ID UUID,

    PRIMARY KEY (POST_ID, TAG_ID, BLOG_ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(CONTENT_ID),
    FOREIGN KEY (TAG_ID, BLOG_ID) REFERENCES BLOG_TAGS(ID, BLOG_ID)

);