spring:
  application:
    name: Stop Newsletter 1.0
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  main:
    allow-bean-definition-overriding: true


databases:
  main:
    datasource:
      url: jdbc:postgresql://localhost:6543/postgres
      username: postgres
      password: Sylwia70
      hikari:
        schema: stop
        poolName: mainDataSource
    packages: com.stopnewsletter.backend.scene
    liquibase:
      changeLog: classpath:db/changelog-main.yaml
  scene:
    datasource:
      url-prefix: jdbc:postgresql://localhost:6543/
    cache:
      maximumSize: 2
      expireAfterAccess: 10
    liquibase:
      changeLog: classpath:db/changelog-scene.yaml
  catalog:
    packages: >
      com.stopnewsletter.backend.blog,
      com.stopnewsletter.backend.content,
      com.stopnewsletter.backend.source

notion:
  version: 2022-06-28
  baseUrl: api.notion.com/v1
  authorization: M7DEsPHdt3HOkhHot9a4DwbZxwfcJRsa7MYRoasVzU




